name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: git clone https://github.com/clue/framework-x.git source/
      - run: make
      - run: make served
      - run: make test
      - run: git config --global user.name "GitHub Actions" && git config --global user.email "actions@github.com"
      - run: git config --global url."https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - run: make deploy
        if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
